### ISSUE TITLE
Windows support (Python 2.7 => MSVC 2008)

### ISSUE THREAD

**Issue by Jorge-C** [mengyao/Complete-Striped-Smith-Waterman-Library#16]
Hi! A scikit-bio contributor has been working on compiling it under windows, using MSVC 2008, but hit some problems with your library. The first changes were to define a couple of variables at the beginning of the scope, but he's now getting a segmentation fault, see a few more details in [this issue](https://github.com/biocore/scikit-bio/issues/702). Do you have any hints? Thank you!

**Comment by jeffdaily** [comment]
Sorry to revive an old thread, but I wanted to point out that my https://github.com/jeffdaily/parasail sequence alignment project has a CMake build that works natively on windows.
