### ISSUE TITLE
silence warnings

### ISSUE THREAD

**Issue by zeeev** [mengyao/Complete-Striped-Smith-Waterman-Library#21]
I'm using SSW as a submodule and it is awesome. Is there anyway the code could be compiled in a no-warning mode?  I want to suppress the following warnings:

When maskLen < 15, the function ssw_align doesn't return 2nd best alignment information.

**Comment by mengyao** [comment]
Dear Zev,

Thank you for your interests in this library.

To get rid of this warning, you can just comment off line 799 in ssw.c.

Yours,

Mengyao

**Comment by jewmanchue** [comment]
Mengyao,

Thank you for responding.  Since I'm using SSW as a github submodule I'm not sure if I can push local submodule changes to my repository?

--Zev

**Comment by mengyao** [comment]
Dear Zev,

I think you can fork SSW to your own account, then you can do anything to it freely.

Yours,

Mengyao
