### ISSUE TITLE
Please tag a released version

### ISSUE THREAD

**Issue by satta** [mengyao/Complete-Striped-Smith-Waterman-Library#33]
Hi, I am looking to package this for Debian. To make it possible for me to uniquely reference the packaged version (and watch for updates!), I am kindly asking that you provide versioned tags in this GitHub repository. Thanks in advance!

**Comment by mengyao** [comment]
Hi,

I’ve put a versioned tag here:
https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/releases <https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/releases>

Please let me know, if you meet any problem with it.

Many thanks,

Mengyao

**Comment by satta** [comment]
Great, many thanks!

**Comment by satta** [comment]
FYI, it's in Debian now: https://tracker.debian.org/pkg/libssw

**Comment by mengyao** [comment]
Thank you very much for making this available.

Yours,

Mengyao
