### ISSUE TITLE
SEQ and QUAL have different lengths

### ISSUE THREAD

**Issue by sdwfrost** [mengyao/Complete-Striped-Smith-Waterman-Library#42]
I can't process the SAM output from `ssw_test` with `samtools` as the sequence length and quality score are different lengths:

`ssw_test -m 1 -x 2 -o 4 -e 3 -f 14 -r -s -h -c ref.fas query.fastq > query.sam`

followed by

```
samtools view -bS query.sam
```

gives

```
[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] parse error at line 3
[bam_flagstat_core] Truncated file? Continue anyway.
```

The first line of my SAM file is:

```
@HD	VN:1.4	SO:queryname
@SQ	SN:EU239217.1	LN:3212
NS500125:171:H5WMJAFXX:4:21605:21022:14089	16	EU239217.1	2682	5	104S14=32S	*	0	0	TTGTATTGAAAAACTCACTTAGATTTTATATTTTGTTATATTCTAAAAGTTTTATGGTTTTTCATTTTGCATTTGTGTGTATGATTCATTTTGAGTTCATTTTTGAGAAAGGTATAAAGTCTGTGCCTGGATTAATTTTTTTTTTTTTTT	/E<EE<EEEE/<EE	AS:i:14	NM:i:150	ZS:i:10
```

The quality string is way shorter than the sequence.

**Comment by mengyao** [comment]
Dear Simon,

I apologize for the error.

It has been fixed. Please clone and try the latest version.

Please let me know, if you find any other problem.

Many thanks,

Mengyao

**Comment by sdwfrost** [comment]
Almost! It appears that the quality score is one base shorter than the sequence.

**Comment by mengyao** [comment]
I just made a update. Please have a check.

Sorry for the error.
