### ISSUE TITLE
Comments Causing Confusion

### ISSUE THREAD

**Issue by spikeliu** [mengyao/Complete-Striped-Smith-Waterman-Library#51]
https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/blob/4140dcf7459e69293a51d9397bc4df7ba4073445/src/ssw.h#L43
I think the name here should be **ref_end2**, not **read_end2**, based on what you actually wrote in the structure declaration. Also, the description on this line should be modified.

**Comment by mengyao** [comment]
Thank you for this comment. Just fixed.
