### ISSUE TITLE
what should I do if I don't want to alignment result with soft clip sequence("S")?

### ISSUE THREAD

**Issue by ydLiu-HIT** [mengyao/Complete-Striped-Smith-Waterman-Library#54]
If I want to align sequence  A to sequence B, and I want to do global alignment rather than local alignment, so what can I do to prevent the alignment result with soft clip("S" in the begin or the end of sequence A)?

Thank you!!!

**Comment by jeffdaily** [comment]
SSW is great for local alignment. But if you’re looking for something similar for global alignment perhaps try https://github.com/jeffdaily/parasail.

**Comment by ydLiu-HIT** [comment]
Thanks for your help. SSW is a great job for local alignment and I am using. AND I suggest that your group can add some functions which can do global or semi-local alignment, or provide a parameter for users to choose. This is just a small suggestion, Thank you.
