### ISSUE TITLE
segmentation fault (core dumped) when running pyssw.py

### ISSUE THREAD

**Issue by MohdKhairulNizam** [mengyao/Complete-Striped-Smith-Waterman-Library#77]
Hi,

I am new to bioinformatics so I apologize if my question sounds too simple or trivial

I tried running pyssw.py script on the demo dataset and it ran perfectly. However, when I tried the script on a larger dataset which I downloaded from SRA, I received this error: segmentation fault (core dumped)

Can anyone help me?

Thanks

**Comment by mengyao** [comment]
I fixed some bugs recently. Please have a try of the new version.
