### ISSUE TITLE
incorrect alignment

### ISSUE THREAD

**Issue by boristim66** [mengyao/Complete-Striped-Smith-Waterman-Library#80]
Dear developers!
Analysis of nearly 100,000 unique hCoV-19 protein sequences from the GISAID database found an alignment shift for several closely related sequences, samples of which are attached. As you can see, these samples are initially aligned, but the program produces ref_begin1 = 1 and read_begin1 = 2, which leads to a shift in the result. I hope you can detect and correct this bug .
command line:  -p -c testcopy2.fa query.fasta

Sincerely, Boris
[ssw_example.zip](https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/files/7337267/ssw_example.zip)
/

**Comment by mengyao** [comment]
Thanks, all. This bug is fixed in the new version.
