### ISSUE TITLE
No libssw.so after executing 'make' in the src folder

### ISSUE THREAD

**Issue by mcolic** [mengyao/Complete-Striped-Smith-Waterman-Library#82]
Hi,

After I execute '**make**' in the src folder there is no libssw.so file that needs to be copied into my program. I have also tried gcc compiling: **gcc -Wall -O3 -pipe -fPIC -shared -rdynamic -o libssw.so ssw.c ssw.h** - but gives me a clang error: **clang: error: cannot specify -o when generating multiple output files**! Can you please assist with this?

Thank you.

**Comment by mengyao** [comment]
Please run ‘make default’.

Yours,

Mengyao

**Comment by mcolic** [comment]
Hi Mengyao,

Thank you for a quick response. When I do run the make default I do get both libssw.so and ssw_lib.py, but when I need to use the module it tells me that it's an incompatible architecture (have 'arm64', need 'x86_64'). I should specify that I am running this on MacBook with M1 chip.
Thank you.
Best,
Medina

**Comment by mengyao** [comment]
Hi Medina, 

Arm64 is for MacBook M1 chip, while x86_64 is for Intel CPUs. 

When you compile SSW on your MacBook, it will generate the libssw.so for arm64. 

Your error looks like your python program expects a x86_64 libssw.so. I suggest you compile SSW on a linux machine. The libssw.so will be for x86_64.

I will try to make a new release that have compiled binary files for different systems soon. 

Bests,

Mengyao

**Comment by mcolic** [comment]
Hi Mengyao,

I have switched to an Intel MacBook. I installed the library with 'make default', and have both files libssw.so and ssw_lib.py. However, I am trying to use the library within another package tuba-seq (https://github.com/petrov-lab/tuba-seq), and when I use the scripts that are dependent on the libssw.so, I keep getting the error saying: "libssw.so does not exist in PATH" - which comes from one of the scripts in the tuba-seq package. I am not sure how to resolve this error. Can you please provide any assistance or suggestions?

Thanks,
Medina

**Comment by mengyao** [comment]
According to the error message, I think you just need to add the libssw.so path into your PATH viable. You may need to add export PATH=<libssw.so path>:PATH in your .bashrc file.

Mengyao
