### ISSUE TITLE
Please expose s_align.flag in the C++ wrapper

### ISSUE THREAD

**Issue by marcelm** [mengyao/Complete-Striped-Smith-Waterman-Library#86]
The recently added `flag` attribute of the `s_align` struct is not exposed in the C++ wrapper.

After upgrading our copy of SSW, I noticed that we now sometimes get the message: "Warning: The alignment path of one pair of sequences may miss a small part." and an incorrect CIGAR (which does not match the query length). It appears that the `s_align.flag` attribute was added recently to signal failed alignments, but the C++ interface does not expose this, so in our case we cannot distinguish successful from failed alignments.

**Comment by mengyao** [comment]
s_align.flag will be the return value of c++ API Align function in the new release

**Comment by marcelm** [comment]
Nice, thanks a lot!
