### ISSUE TITLE
missing the begin of the alignments in the output

### ISSUE THREAD

**Issue by SyedKumailHussainNaqvi** [mengyao/Complete-Striped-Smith-Waterman-Library#88]
Hi @mengyao 
I am using the Python wrapper ssw_lib.py with this command 
python pyssw.py "/home/biolab/src/target_peptide.fasta" "/home/biolab/src/query_peptide.fasta"
but  I'm missing the begin of the alignments in the output.

When maskLen < 15, the function ssw_align doesn't return 2nd best alignment information.
target_name: 1acy_L
query_name: 1acy_p
optimal_alignment_score: 6
strand: +
target_end: 76
query_end: 18

When maskLen < 15, the function ssw_align doesn't return 2nd best alignment information.
target_name: 1n0x_H
query_name: 1acy_p
optimal_alignment_score: 4
strand: +
target_end: 26
query_end: 23

When maskLen < 15, the function ssw_align doesn't return 2nd best alignment information.
target_name: 1n0x_L
query_name: 1acy_p
optimal_alignment_score: 6
strand: +
target_end: 75
query_end: 18

When maskLen < 15, the function ssw_align doesn't return 2nd best alignment information.
target_name: 1qgc_A
query_name: 1acy_p
optimal_alignment_score: 6
strand: +
target_end: 124
query_end: 18

When maskLen < 15, the function ssw_align doesn't return 2nd best alignment information.
target_name: 1vrk_A
query_name: 1acy_p
optimal_alignment_score: 4
strand: +
target_end: 5
query_end: 18

When maskLen < 15, the function ssw_align doesn't return 2nd best alignment information.
target_name: 1acy_L
query_name: 1n0x_p
optimal_alignment_score: 4
strand: +
target_end: 25
query_end: 16

When maskLen < 15, the function ssw_align doesn't return 2nd best alignment information.
target_name: 1n0x_H
query_name: 1n0x_p
optimal_alignment_score: 4
strand: +
target_end: 24
query_end: 16

[fasta files.zip](https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/files/11888654/fasta.files.zip)

**Comment by mengyao** [comment]
You can use -c option to get the full info.

Mengyao

**Comment by SyedKumailHussainNaqvi** [comment]
Thanks you so much for your kind reply and guidance....
its done.
target_name: 1acy_L
query_name: 1acy_p
optimal_alignment_score: 6	
strand: +	
target_begin: 68	
target_end: 76	
query_begin: 10	
query_end: 18

Target:      68	GSGSRTDFT	76
               	|*|*****|
Query:       10	GPGRAFYTT	18

target_name: 1n0x_H
query_name: 1acy_p
optimal_alignment_score: 4	
strand: +	
target_begin: 15	
target_end: 26	
query_begin: 12	
query_end: 23

Target:      15	GASVKVSCQASG	26
               	|**********|
Query:       12	GRAFYTTKNIIG	23
...
Target:      33	GTVMRSLG	40
               	|***|**|
Query:        8	GHAVRAIG	15
