### ISSUE TITLE
wrong score for very large sequences

### ISSUE THREAD

**Issue by tolot27** [mengyao/Complete-Striped-Smith-Waterman-Library#9]
I've a very large protein sequence (the largest known) with 36851 aa (inkl. hard masked regions)

The self alignment is stopped at 5220 and the optimal alignment score is the maximun of signed short (16 bit):

```
./ssw_test -o 13 -e 2 -p longest.fa longest.fa
optimal_alignment_score: 32767  suboptimal_alignment_score: 32767   strand: +   target_end: 5220    query_end: 5220
```

It looks like there are some hard-coded limits. There are much more sequences larger than 5220 aa (i. e. titins). Please can you investigate this?

A simple test can be made with [V5FZX2](http://www.uniprot.org/uniprot/V5FZX2), which is just 5573 aa, but also gets not correctly scored.

**Comment by jeffdaily** [comment]
@tolot27 I have a 32bit implementation of the SW algorithm that produces the correct score for V5FZX2 and your scoring criteria (B50, open 13, extend 2).  I do not output the traceback, however.  Would this still be of value to you?
____________________________________________________

Jeff Daily
Scientist
ADVANCED COMPUTING, MATHEMATICS, AND DATA DIVISION
High Performance Computing Group

Pacific Northwest National Laboratory
902 Battelle Boulevard
P.O. Box 999, MSIN J4-30
Richland, WA 99352 USA
Tel: 509-372-6548
Fax: 509-372-4720 
jeff.daily@pnnl.gov
www.pnnl.gov
